version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - automated
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    assignees:
      - sbs44

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      include: scope
    labels:
      - automated
    groups:
      all-actions:
        applies-to: version-updates
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    assignees:
      - sbs44
